services:
  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    container_name: backend-core-service
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: diagramador-db
      POSTGRES_PORT: 5432
      UPLOADS_DIR: uploads
    expose:
      - "8000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - default
      - existing-core

  nest-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-nest-gateway
    restart: unless-stopped
    environment:
      PORT: 8000
      FASTAPI_BASE_URL: http://core-service:8000
    ports:
      - "8010:8000"
    depends_on:
      - core-service

networks:
  existing-core:
    external: true
    name: ficct-segundo-parcial-sw2-web_default
